// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dycdnqoixwlcxonzrmql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5Y2RucW9peHdsY3hvbnpybXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNTQwMTAsImV4cCI6MjA1NjczMDAxMH0.6z8wFU9rMONxhLONqFseef5mqkSHNST7psGP3U9kF1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);